#!/usr/bin/env node

const fs = require('fs')


const TRUNCATE_DIR = 'bin'


// http://stackoverflow.com/a/34597104/586382
// NPM will run prepublish script after `npm install` (https://docs.npmjs.com/misc/scripts)
// This ensures that when script is executed using `npm *` it is run only when the command is `npm publish`.
const npm_config_argv = process.env.npm_config_argv
if(npm_config_argv && JSON.parse(npm_config_argv).original[0] === 'publish')
  fs.readdir(TRUNCATE_DIR, function(err, files)
  {
    if(err) throw err

    files.forEach(function(file)
    {
      fs.truncateSync(TRUNCATE_DIR+'/'+file, 0)
    })
  })
